name: Visual Regression Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: npm ci
      - name: Build storybook
        run: npm run build-storybook
      - name: Run Loki
        run: npm run loki:update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
