name: Visual Regression Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build-storybook
      - run: npm run loki:update
